spring:
  application:
    name: auth-server
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID:}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "http://localhost:8085/auth/login/oauth2/code/{registrationId}"
            client-name: Google
        provider:
          google:
            issuer-uri: https://accounts.google.com

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
    ip-address: 127.0.0.1
    non-secure-port: ${server.port}
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}

server:
  port: 8081
  servlet:
    context-path: /auth