spring:
  application:
    name: my-client-app   # matches 'application' column in DB
  profiles:
    active: dev           # matches 'profile' column in DB
  cloud:
    config:
      label: main         # matches 'label' column in DB
      uri: http://localhost:8888
  config:
    import: "configserver:"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: false
    hostname: localhost
    ip-address: 127.0.0.1
    non-secure-port: ${server.port}
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}


server:
  port: 9091
  servlet:
    context-path: /api